name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    environment: cron
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download modules
        run: go mod download

      - name: Test
        run: go test -v ./...

      - name: Fetch latest data
        run: ./scrape-and-push.sh
        env:
          AMTRACK_SHEET: ${{ secrets.AMTRACK_SHEET }}
          AMTRACK_OPEN_STATES_KEY: ${{ secrets.AMTRACK_OPEN_STATES_KEY }}
          AMTRACK_GOOGLE_CLIENT_SECRET: ${{ secrets.AMTRACK_GOOGLE_CLIENT_SECRET }}
